version: '3.6'
services:
  apix2019-microservice-finder-java:
    image: sensedia/apix2019-microservice-finder-java
    container_name: finder
    ports:
      - "5050:8080"
    environment:
      FINDER_CONFIG_FILE: ${FINDER_CONFIG_FILE}
    networks:
      - apix2019
networks:
  apix2019:
    external:
      name: apix2019infra_apix2019
